In [2]:
import numpy as np

arr = np.array([1, 2, 3])

list1 = arr.tolist()
print(f'List: {list1}')

List: [1, 2, 3]


In [5]:
import numpy as np
  
n_array = np.array([[35, 15, 5],
                    [30, 44, 2],
                    [11, 45, 77]])
  
print("Numpy Matrix is:")
print(n_array)
  
trace = np.trace(n_array)
  
print("\nTrace of given 3X3 matrix:")
print(trace)

Numpy Matrix is:
[[35 15  5]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
156


In [1]:
num = [2, 3, 4]
print()
print(all(x > 5 for x in num))
print(all(x >4 for x in num))
print()


False
False



In [8]:
import numpy as np
in_num1 = 6
in_num2 = 4
  
print ("1st Input  number : ", in_num1)
print ("2nd Input  number : ", in_num2)
    
out_num = np.subtract(in_num1, in_num2) 
print ("Difference of two input number : ", out_num) 

1st Input  number :  6
2nd Input  number :  4
Difference of two input number :  2
